### ISSUE TITLE
No module named 'ts_dataset' when pickle.load

### ISSUE THREAD

**Issue by yangzhaogit** [sebastianpinedaar/MMAML-TSR#2]
Sorry, I get an error as below. I cannot load the datasets pickled out. I don't know how to fix the issue. May I ask your help ? Thanks.

Traceback (most recent call last):
  File ".\run_MAML.py", line 353, in <module>
    main(args)
  File ".\run_MAML.py", line 136, in main
    train_data_ML = pickle.load( open( "../data/TRAIN-"+dataset_name+"-W"+str(window_size)+"-T"+str(task_size)+"-ML.pickle", "rb" ) )
ModuleNotFoundError: No module named 'ts_dataset'

**Comment by sebastianpinedaar** [comment]
Hi,

be sure that you execute the file run_MAML.py from the code/ folder, not from the root MMAML-TSR. Make sure that "code/" is your working directory in the IDE you are using.

Please. Let me know if it works.
