### ISSUE TITLE
About Data-set-split.ods?

### ISSUE THREAD

**Issue by jackstramp** [sebastianpinedaar/MMAML-TSR#4]
What is the Data-set-split.ods file?
the code is in  load_data_pollution

    # split_info = pd.read_excel("../Data/Data-set-split.ods", engine="odf", sheet_name="Pollution")
    # split_info = split_info.iloc[:5, [0,2]]
    # split_info["City_abb"] = [city[:3] for city in split_info.City]
    # split_info = split_info.set_index("City_abb")

**Comment by sebastianpinedaar** [comment]
It is a file for specifying the splits of the meta-training set. I just uploaded it.

However, for the two datasets of the examples, you can simply download the data from here:

https://www.dropbox.com/sh/yds6v1uok3bjydn/AAC5GRWw0F3clopRlk00Smvza?dl=0
